name: Build Debug APK

on:
  push:
    branches:
      - main  # 触发分支，可以根据需要修改
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # 检出代码

    - name: set up JDK 11  # 设置JDK版本
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2  # 设置Android SDK

    - name: Grant execute permission for gradlew  # 给予gradlew执行权限（如果你的项目有这个需求）
      run: chmod +x gradlew

    - name: Build with Gradle  # 使用Gradle构建Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK  # 上传构建的APK到Artifact（可选）
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
